# Generated by Django 5.1.1 on 2026-04-09 17:09

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_category'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('queryset', django.db.models.manager.Manager()),
            ],
        ),
    ]
