# Generated by Django 5.1.1 on 2026-04-09 17:14

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('qobjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
